name: restaurant_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: any
  flutter_svg:
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.0.15
  http: ^0.13.5
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  color: '#FE724C'
  image: assets/img/logo.png
  andorid: true

  android_12:
    image: assets/img/logo.png
    color: '#FE724C'
  web: false


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - 'assets/img/'
    - 'assets/icons/'
    - 'assets/json/local_restaurant.json'

  fonts:
    - family: sofiapro
      fonts:
        - asset: assets/fonts/sofiapro-light.otf